# -*- coding: utf-8 -*-
"""DecisionTreeClassifier_in_Diabete_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pt-qfmJOX4PygQnoehpm5ydshqoWORu2
"""

import pandas as pd
import numpy as np
data=pd.read_csv('/content/drive/MyDrive/diabetes.csv')

data.head()

x=data.drop('Outcome',axis=1)
y=data['Outcome']

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.tree import DecisionTreeClassifier
Classifier=DecisionTreeClassifier(criterion='entropy')
Classifier.fit(xtrain,ytrain)

ypred=Classifier.predict(xtest)

from sklearn.metrics import accuracy_score
print(accuracy_score(ytest,ypred))

from sklearn.tree import export_graphviz
import graphviz

graphviz.Source(export_graphviz(Classifier,feature_names = x.columns, filled = True))